service: nest-lambda-docker

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  # - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  stage: dev
  profile: lambda-docker
  ecr:
    images:
      appimage:
        path: ./

functions:
  main:
    image:
      name: appimage
      command:
        - dist/lambda.handler
      entryPoint:
        - '/lambda-entrypoint.sh'
    # handler: src/lambda.handler
    events:
      - s3:
          bucket: churn-number-upload-devr
          event: s3:ObjectCreated:*
          